#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/dimdaemon`
case "$1" in
  start)
    stat_busy "Starting dimdaemon"
    [ -z "$PID" ] && /usr/bin/dimdaemon 
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon dimdaemon
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping dimdaemon"
    [ ! -z "$PID" ]  && kill $PID > /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon dimdaemon
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
